sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t golthem/docker-react-test -f Dockerfile.dev .

script:
    - docker run -e CI=true golthem/docker-react-test npm run test